version: '3.5'
services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        - UID
        - USER_NAME
    working_dir:
      /app
    volumes:
      - ./app:/app
    user: ${USER_NAME}
    networks:
      - internal
  node:
    container_name: ${COMPOSE_PROJECT_NAME}_node
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    command: ["node", "websocket-relay.js", "supersecret", "8081", "8082"]
    working_dir:
      /app
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./app:/app
    networks:
      - internal
  nginx:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html:ro
    depends_on:
      - app
    networks:
      - internal
networks:
  internal: