version: '3.5'
services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - UID
        - USER_NAME
    working_dir:
      /app
    volumes:
      - ./app:/app
    user: ${USER_NAME}
    networks:
      - internal
  nginx:
    image: nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html:ro
    depends_on:
      - app
    networks:
      - internal
networks:
  internal: